version: '3.4'
services:
  train:
    image: titanic:dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    entrypoint: [
      "make", "train"
    ]
  survive:
    image: titanic:dev
    depends_on:
      - train
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - .:/code
    entrypoint: [
      "uvicorn", "app.main:app", "--reload", "--port" ,"5000", "--host", "0.0.0.0"
    ]
