apiVersion: v1
kind: Service
metadata:
  name: titanic-service
spec:
  type: NodePort
  selector:
    app: titanic # pod labels
  ports:
    - protocol: TCP
      port: 80 # expose
      targetPort: 5000 # container